In [14]:
import pandas as pd
import json

In [15]:
get_district = '永康區'
get_weather = '晴'
# hour = current_time.hour
hour = 17

In [16]:
df_risk = pd.read_csv('csv_file/for_web.csv', index_col=0)
district_mask = df_risk['district'] == get_district
weather_mask = df_risk['weather'] == get_weather
time_mask = df_risk['time_slot'] == hour
df_result = df_risk[district_mask & weather_mask & time_mask]
df_risk = df_risk.drop(['time_slot', 'district', 'weather', 'cause', 'district'], axis=1)
df_risk

,risk_high,risk_medium,risk_low
0,"[146360, 148484, 170595]",[183717],"[156145, 146363]"
1,[199841],[146360],"[181633, 188834, 170595, 148484, 177866, 16468..."
2,[146360],"[148483, 159980]","[160832, 170595, 155269, 165103, 151889, 17573..."
3,[],[148484],"[146360, 146363, 183717, 179991]"
4,[],[167144],"[146360, 152315, 148484]"
...,...,...,...
6211,[],[],[]
6212,[],[],[]
6213,[],[],[]
6214,[],[],[]
6215,[],[],[]

In [17]:
df2 = pd.read_csv('csv_file/net_address.csv', index_col=0)
df2

       grid_id                        coordinate                     address
0       350626        23.093183032,120.427687834                     臺南市白河區段
1       243101        23.093183032,120.316367834           臺南市新營區忠政里中正路段號民治路
2       240551        23.093183032,120.313727834  臺南市新市區大營里省道臺1線段口大營里區道南140線
3       109651        23.093183032,120.178207834              臺南市佳里區延平路段口和平街
4       240126        23.093183032,120.313287834            臺南市新營區段新營醫院急診入口旁
...        ...                               ...                         ...
29483   203114        22.922463032,120.274567834   臺南市歸仁區段武東里中正南路北往南(近歸仁十六路)
29484   253586        22.967783032,120.326927834            臺南市關廟區南雄路2段512附近
29485   122488        23.054903032,120.191407834        臺南市安南區本原街1段口巷弄原佃幹36號
29486   122481  23.057983032000003,120.191407834              臺南市安南區本原街2106段
29487   167683        22.991103032,120.238047834               臺南市東區建東街段58北側

[29488 rows x 3 columns]

In [18]:
str_risk_high = df_risk['risk_high'].values
str_risk_medium = df_risk['risk_medium'].values
str_risk_low = df_risk['risk_low'].values

print(len(str_risk_low))
str_risk_low

6216

array(['[156145, 146363]',
       '[181633, 188834, 170595, 148484, 177866, 164686, 188062]',
       '[160832, 170595, 155269, 165103, 151889, 175738, 202810, 152315, 176991]',
       ..., '[]', '[]', '[]'], dtype=object)

In [32]:
ls_risk_high = []
ls_risk_medium = []
ls_risk_low = []

for i in range(len(str_risk_low)-1):
    ls_risk_high += json.loads(str_risk_high[i])
for i in range(len(str_risk_low)-1):
    ls_risk_medium += json.loads(str_risk_medium[i])
for i in range(len(str_risk_low)-1):
    ls_risk_low += json.loads(str_risk_low[i])

ls_risk_low

[156145,
 146363,
 181633,
 188834,
 170595,
 148484,
 177866,
 164686,
 188062,
 160832,
 170595,
 155269,
 165103,
 151889,
 175738,
 202810,
 152315,
 176991,
 146360,
 146363,
 183717,
 179991,
 146360,
 152315,
 148484,
 146360,
 164688,
 148484,
 194853,
 160832,
 163394,
 170595,
 146360,
 146360,
 159980,
 148484,
 151889,
 161239,
 148484,
 160838,
 169366,
 151889,
 168897,
 146360,
 156571,
 146360,
 146360,
 148484,
 148484,
 156571,
 196547,
 167235,
 178245,
 173190,
 181192,
 201544,
 164686,
 171409,
 169361,
 187218,
 180375,
 157848,
 196121,
 193054,
 169694,
 194852,
 151464,
 165482,
 175218,
 177019,
 156995,
 173191,
 170951,
 164232,
 169673,
 157390,
 185870,
 167568,
 151889,
 178193,
 162965,
 175639,
 185440,
 207971,
 179108,
 177841,
 146368,
 170595,
 156571,
 161669,
 167619,
 168423,
 155726,
 164687,
 203315,
 168091,
 193054,
 143810,
 169671,
 177422,
 181265,
 174866,
 184660,
 162965,
 179097,
 169694,
 165471,
 177441,
 171042,
 160357,
 151464,
 151465,
 196969,
 181227,
 173616,
 177011,
 182964,
 194429,
 191423,
 202049,
 163394,
 167619,
 159971,
 167624,
 172682,
 170603,
 190508,
 208814,
 176562,
 160407,
 173532,
 176166,
 190509,
 169713,
 151028,
 159126,
 168502,
 152315,
 164669,
 171396,
 160357,
 194853,
 173991,
 187178,
 168844,
 167569,
 159125,
 166357,
 185878,
 162937,
 166369,
 193961,
 204506,
 178715,
 162557,
 187588,
 146789,
 176165,
 191015,
 163751,
 188842,
 165869,
 190125,
 154866,
 187539,
 164600,
 159132,
 151889,
 150179,
 176917,
 190613,
 177019,
 156541,
 175716,
 148484,
 200808,
 151888,
 172662,
 189687,
 159547,
 163325,
 151038,
 156964,
 151452,
 171019,
 174386,
 199511,
 173944,
 185020,
 194430,
 179953,
 192302,
 166719,
 176576,
 188912,
 159507,
 200725,
 158698,
 193953,
 164690,
 183779,
 176579,
 146360,
 162553,
 164175,
 192282,
 163796,
 165927,
 176087,
 165927,
 165103,
 181634,
 160832,
 159553,
 188423,
 195721,
 153166,
 199954,
 187986,
 162964,
 165078,
 161634,
 194852,
 171817,
 161710,
 164654,
 164206,
 197743,
 175737,
 182906,
 153149,
 146367,
 148484,
 180326,
 185836,
 202446,
 162032,
 156147,
 173108,
 163351,
 188856,
 194427,
 187588,
 155269,
 199044,
 177384,
 158698,
 191371,
 187149,
 161205,
 165078,
 173145,
 182467,
 193956,
 156965,
 188906,
 152716,
 162966,
 188410,
 156571,
 188413,
 195646,
 175711,
 174849,
 185874,
 165507,
 190611,
 179511,
 179512,
 157005,
 164243,
 161286,
 188423,
 160410,
 187963,
 179918,
 197795,
 178216,
 191441,
 164243,
 187578,
 194429,
 143810,
 150179,
 166359,
 170119,
 176136,
 164265,
 193550,
 167632,
 188881,
 186353,
 167570,
 167572,
 182481,
 190135,
 198250,
 164234,
 153165,
 158286,
 190574,
 180369,
 181622,
 200381,
 189278,
 169247,
 149761,
 196546,
 165966,
 190547,
 156571,
 176543,
 175715,
 170179,
 180838,
 153162,
 170552,
 160410,
 189275,
 185437,
 155269,
 183818,
 147211,
 165872,
 166391,
 178652,
 165116,
 152734,
 188030,
 192673,
 170978,
 177410,
 185876,
 185445,
 187178,
 169343,
 168418,
 146364,
 175735,
 153147,
 149756,
 159983,
 148484,
 185509,
 185512,
 164691,
 196920,
 174865,
 149331,
 173142,
 190508,
 200381,
 165871,
 148909,
 161258,
 164686,
 161260,
 167143,
 192707,
 151038,
 172338,
 177034,
 156651,
 154508,
 147727,
 159631,
 150289,
 153683,
 172361,
 147292,
 162589,
 152396,
 155374,
 158336,
 156651,
 153271,
 156650,
 151531,
 155374,
 163854,
 142182,
 147727,
 147292,
 163854,
 147292,
 159206,
 164270,
 158336,
 168963,
 151108,
 151949,
 147726,
 160461,
 149844,
 157528,
 144284,
 163038,
 170658,
 162595,
 160931,
 148961,
 160038,
 164266,
 174509,
 159215,
 160880,
 160439,
 174498,
 152361,
 153257,
 155828,
 166013,
 162177,
 153670,
 156651,
 152368,
 148980,
 176183,
 164759,
 157087,
 148546,
 162179,
 173635,
 146022,
 167718,
 152361,
 163850,
 158316,
 164270,
 149405,
 157906,
 152380,
 163005,
 162205,
 144740,
 143016,
 148136,
 152843,
 164268,
 146454,
 151097,
 160477,
 176184,
 167312,
 157934,
 153271,
 155810,
 155794,
 164275,
 149385,
 160042,
 151097,
 159650,
 148547,
 163493,
 162598,
 163440,
 157523,
 151988,
 157470,
 155361,
 142179,
 161743,
 157081,
 151545,
 151564,
 152367,
 154937,
 163858,
 160014,
 144770,
 161737,
 153666,
 142622,
 150298,
 154491,
 156646,
 154491,
 151549,
 156671,
 152419,
 164267,
 154494,
 143013,
 143912,
 155389,
 163022,
 166049,
 157086,
 153683,
 159226,
 163063,
 158316,
 156226,
 143875,
 158786,
 155371,
 150286,
 164271,
 161299,
 150265,
 164315,
 148572,
 157055,
 154082,
 167719,
 143464,
 157967,
 153683,
 169366,
 154522,
 165563,
 163018,
 159650,
 174485,
 161359,
 155386,
 146059,
 160879,
 177043,
 155795,
 174485,
 163478,
 157527,
 164314,
 148539,
 147292,
 157919,
 150268,
 142181,
 156646,
 152394,
 159164,
 148141,
 151566,
 146453,
 166838,
 151127,
 146043,
 163853,
 143872,
 158336,
 170660,
 172361,
 174506,
 160044,
 166008,
 176185,
 143870,
 172367,
 150288,
 156225,
 141777,
 151947,
 159630,
 144739,
 163892,
 146452,
 146454,
 153256,
 145165,
 159199,
 154974,
 156226,
 156650,
 163051,
 150284,
 147707,
 162173,
 165139,
 144340,
 150715,
 155389,
 153662,
 168127,
 149002,
 161746,
 160037,
 165557,
 142187,
 143874,
 149001,
 159630,
 166416,
 141777,
 143889,
 147349,
 161301,
 142621,
 148577,
 158817,
 142630,
 157485,
 166838,
 153271,
 166465,
 148130,
 154108,
 143013,
 158316,
 147725,
 163857,
 146487,
 174937,
 150681,
 145596,
 158782,
 148545,
 162145,
 157060,
 148133,
 145201,
 152821,
 155799,
 153657,
 151969,
 159617,
 154491,
 157485,
 160015,
 154508,
 174910,
 155819,
 161346,
 147293,
 142631,
 157555,
 161750,
 148133,
 153617,
 139185,
 141302,
 139162,
 142557,
 141276,
 141289,
 151070,
 125135,
 153617,
 116211,
 143854,
 147234,
 142557,
 131511,
 131511,
 158313,
 148955,
 151070,
 130217,
 125135,
 124272,
 143404,
 137910,
 151070,
 143854,
 131511,
 116212,
 147234,
 125141,
 131511,
 143404,
 120896,
 158726,
 152781,
 153617,
 142161,
 154899,
 125142,
 116639,
 160864,
 137444,
 143854,
 130675,
 116212,
 138743,
 124728,
 142969,
 131963,
 119188,
 114933,
 131092,
 116212,
 142553,
 115360,
 153636,
 131111,
 141289,
 139148,
 157037,
 142544,
 117906,
 131101,
 146371,
 145546,
 140430,
 154904,
 139162,
 131104,
 133664,
 142565,
 141288,
 151919,
 136625,
 161716,
 128952,
 135738,
 131073,
 153193,
 152781,
 128949,
 140886,
 125141,
 140027,
 131100,
 142556,
 137492,
 157462,
 126856,
 154908,
 138750,
 149807,
 135353,
 126421,
 141289,
 151914,
 130222,
 110272,
 134081,
 134082,
 156171,
 148523,
 158739,
 136215,
 154041,
 134082,
 153191,
 134088,
 140845,
 140430,
 134929,
 124728,
 125982,
 137471,
 132386,
 132388,
 149797,
 124710,
 139185,
 125141,
 125142,
 148535,
 133659,
 148955,
 116640,
 134082,
 131076,
 149351,
 151495,
 148105,
 143404,
 139186,
 137875,
 148084,
 125140,
 130678,
 145947,
 154890,
 137916,
 143434,
 141303,
 137869,
 140446,
 146404,
 154473,
 130217,
 140443,
 124272,
 148507,
 148961,
 140868,
 141700,
 137035,
 120876,
 131084,
 127284,
 143416,
 142557,
 134921,
 150646,
 152356,
 148933,
 117495,
 135354,
 151896,
 148953,
 141301,
 125134,
 124269,
 152782,
 148506,
 158739,
 145524,
 125143,
 141744,
 152344,
 139587,
 138739,
 117496,
 149372,
 139999,
 125137,
 154475,
 139585,
 142162,
 134084,
 145560,
 138296,
 118332,
 156173,
 142977,
 139603,
 127705,
 130217,
 147249,
 124725,
 138298,
 139582,
 146404,
 125141,
 150214,
 159163,
 137885,
 129406,
 131520,
 116641,
 142549,
 144279,
 151081,
 124272,
 116636,
 136160,
 153189,
 147656,
 158313,
 144700,
 130237,
 151067,
 144243,
 125141,
 133655,
 158312,
 126008,
 151483,
 154041,
 150209,
 115281,
 72340,
 145504,
 168394,
 122509,
 90646,
 123417,
 173043,
 148819,
 122509,
 72340,
 123361,
 139971,
 110247,
 94482,
 122941,
 148820,
 120855,
 111512,
 105498,
 137340,
 108029,
 121150,
 92768,
 145922,
 101254,
 93192,
 134409,
 109738,
 108467,
 130132,
 129786,
 102527,
 139093,
 128936,
 135290,
 167116,
 118303,
 68929,
 124261,
 134861,
 148429,
 162864,
 127986,
 119156,
 148821,
 168392,
 135723,
 98315,
 150495,
 136993,
 135722,
 142939,
 132290,
 142512,
 123788,
 133577,
 131403,
 135724,
 116559,
 106776,
 135728,
 141232,
 147543,
 142933,
 145503,
 133569,
 119124,
 122985,
 102151,
 170499,
 120835,
 125508,
 135701,
 147194,
 136161,
 122458,
 105134,
 121246,
 119508,
 123348,
 143366,
 149272,
 77050,
 114428,
 117460,
 147117,
 146353,
 107578,
 144204,
 143795,
 136564,
 125091,
 114019,
 135727,
 102516,
 144567,
 137403,
 143358,
 138281,
 172620,
 98316,
 109709,
 113229,
 123377,
 86354,
 115281,
 119123,
 123800,
 133113,
 153056,
 129738,
 117847,
 122056,
 145450,
 144973,
 148816,
 97846,
 122552,
 140379,
 140381,
 82130,
 143782,
 94970,
 135725,
 122094,
 126789,
 119550,
 122084,
 102151,
 126338,
 134413,
 148822,
 122450,
 59212,
 111445,
 117839,
 143344,
 134413,
 147958,
 127191,
 147201,
 147107,
 122983,
 137432,
 ...]

In [ ]:
ls_coor_low = []